# Font
POWERLEVEL9K_MODE="nerdfont-complete"

# Elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=()
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(os_icon time user context dir vcs status)

# Line Settings
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LPROMPT_ON_NEWLINE=true

# Multiline Prefix and Suffix
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{237}\uE0B6%F{white}%K{237}❯%F{237}%K{default}\uE0B4 "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=""

# Separators and Symbols
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=" "
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=" "
POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL="\uE0B6"
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL="\uE0B6"
POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=""
POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL="\uE0B4"
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%k%F{$POWERLEVEL9K_BACKGROUND}\uE0B4%k \uE0B6"
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%k%F{237}\uE0B4%k \uE0B6"

# OS
POWERLEVEL9K_OS_ICON_BACKGROUND="237"
POWERLEVEL9K_OS_ICON_FOREGROUND="white"

# User
POWERLEVEL9K_USER_ICON="\uF2BD"
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="cyan"
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="237"

# Context
POWERLEVEL9K_ALWAYS_SHOW_USER=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%m \uF108"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="magenta"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="237"

# Dir
POWERLEVEL9K_DIR_BACKGROUND="grey23"
POWERLEVEL9K_DIR_FOREGROUND="blue"
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"

# VCS
POWERLEVEL9K_VCS_BACKGROUND='grey23'
POWERLEVEL9K_VCS_FOREGROUND="black"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='grey23'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="green"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="grey23"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="grey23"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"

# Status
POWERLEVEL9K_STATUS_OK="false"
POWERLEVEL9K_STATUS_BACKGROUND='237'
POWERLEVEL9K_STATUS_OK_BACKGROUND='237'
POWERLEVEL9K_STATUS_OK_FOREGROUND='green'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='237'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'

# Time
POWERLEVEL9K_TIME_BACKGROUND='237'
POWERLEVEL9K_TIME_FOREGROUND='white'

zplug "romkatv/powerlevel10k", as:theme, depth:1